### ISSUE TITLE
hlsdemux: segmentation fault when seeking with FLUSH flag.

### ISSUE THREAD

**Issue by drinkmilk** [ylatuya/gst-plugins-bad#1]
Hi,

I have been playing around with the hlsdemux branch of your repositories and was happy to see that they fix quite a few of the issues I have seen when using the official gstreamer repo.

But ... my minimal gstreamer app segfaults each time I attempt a seek. The line that segfaults (mpegts_packetizer_next_packet mpegtspacketizer.c, line 2471) is:

if (G_UNLIKELY (packet->data_start[0] != 0x47)) {

gdb shows that data_start is indeed NULL, seems like the tsmuxer gets a packet without any data.

This is HLS specific, everything seems fine with other formats.

Disabling the FLUSH flag allows to avoid the segfault but it's then naturally very slow to seek and there seems to be other issues as well.

Any ideas?

Thanks,

Loris

**Comment by ylatuya** [comment]
Hi,
This looks like a bug in tsdemux. To be honest I haven't tried this branch with this demuxer, only with flutsdemux. You can probably "goto done" if the packet is empty.

**Comment by drinkmilk** [comment]
Hey,
I had tried to "goto done" if the packet is empty, but then a chain of other issues were happening instead so ... But it seems to work for me as well with flutsdemux, I will run some more tests and comment back here if there is any issue.

Thanks
